def get_basic_type_cases():
    return [
        ("EQ-basic-001", "None type - None", None),
        ("EQ-basic-002", "Boolean type - True", True),
        ("EQ-basic-003", "Boolean type - False", False),
        ("EQ-basic-004", "Small integer - 0", 0),
        ("EQ-basic-005", "Small integer - 1", 1),
        ("EQ-basic-006", "Small integer - -1", -1),
        ("EQ-basic-007", "Large integer - 2**31", 2**31),
        ("EQ-basic-008", "Large integer - 2**63", 2**63),
        ("EQ-basic-009", "Large integer - -2**63", -(2**63)),
        ("EQ-basic-010", "Very large integer - 2**100", 2**100),
        ("EQ-basic-011", "Very large negative integer - -2**100", -(2**100)),
        ("EQ-basic-012", "Normal string - hello", "hello"),
        ("EQ-basic-013", "Empty string", ""),
        ("EQ-basic-014", "Long normal string", "a" * 10000),
        ("EQ-basic-015", "Unicode string - Chinese and emoji", "中文😀"),
        ("EQ-basic-016", "Long Unicode string", "中文😀" * 1000),
        ("EQ-basic-017", "Special characters string", "\n\t\r\\'\""),
        ("EQ-basic-018", "Bytes type - b'abc'", b"abc"),
        ("EQ-basic-019", "Bytes type - bytes(range(256))", bytes(range(256))),
        ("EQ-basic-020", "Empty bytes", b""),
        ("EQ-basic-021", "Large bytes - 1MB", b"\x00" * (1024 * 1024)),
        ("EQ-basic-022", "Float - 0.0", 0.0),
        ("EQ-basic-023", "Float - 3.14", 3.14),
        ("EQ-basic-024", "Float - -3.14", -3.14),
        ("EQ-basic-025", "Float - very small", 1e-100),
        ("EQ-basic-026", "Float - very large", 1e100),
        ("EQ-basic-027", "Complex number - 1+2j", 1 + 2j),
        ("EQ-basic-028", "Complex number - 0j", 0j),
        ("EQ-basic-029", "Bytearray - bytearray(b'abc')", bytearray(b"abc")),
        (
            "EQ-basic-030",
            "Bytearray - bytearray(range(256))",
            bytearray(range(256)),
        ),
        ("EQ-basic-031", "Empty bytearray", bytearray()),
        ("EQ-basic-032", "Singleton - Ellipsis", Ellipsis),
        ("EQ-basic-033", "Singleton - StopIteration", StopIteration),
    ]
