def get_basic_type_cases():
    return [
        ("BASIC-01", "None type - None", None),
        ("BASIC-02", "Boolean type - True", True),
        ("BASIC-03", "Boolean type - False", False),
        ("BASIC-04", "Small integer - 0", 0),
        ("BASIC-05", "Small integer - 1", 1),
        ("BASIC-06", "Small integer - -1", -1),
        ("BASIC-07", "Large integer - 2**31", 2**31),
        ("BASIC-08", "Large integer - 2**63", 2**63),
        ("BASIC-09", "Large integer - -2**63", -(2**63)),
        ("BASIC-10", "Very large integer - 2**100", 2**100),
        ("BASIC-11", "Very large negative integer - -2**100", -(2**100)),
        ("BASIC-12", "Normal string - hello", "hello"),
        ("BASIC-13", "Empty string", ""),
        ("BASIC-14", "Long normal string", "a" * 10000),
        ("BASIC-15", "Unicode string - Chinese and emoji", "中文😀"),
        ("BASIC-16", "Long Unicode string", "中文😀" * 1000),
        ("BASIC-17", "Special characters string", "\n\t\r\\'\""),
        ("BASIC-18", "Bytes type - b'abc'", b"abc"),
        ("BASIC-19", "Bytes type - bytes(range(256))", bytes(range(256))),
        ("BASIC-20", "Empty bytes", b""),
        ("BASIC-21", "Large bytes - 1MB", b"\x00" * (1024 * 1024)),
        ("BASIC-22", "Float - 0.0", 0.0),
        ("BASIC-23", "Float - 3.14", 3.14),
        ("BASIC-24", "Float - -3.14", -3.14),
        ("BASIC-25", "Float - very small", 1e-100),
        ("BASIC-26", "Float - very large", 1e100),
        ("BASIC-27", "Complex number - 1+2j", 1 + 2j),
        ("BASIC-28", "Complex number - 0j", 0j),
        ("BASIC-29", "Bytearray - bytearray(b'abc')", bytearray(b"abc")),
        ("BASIC-30", "Bytearray - bytearray(range(256))", bytearray(range(256))),
        ("BASIC-31", "Empty bytearray", bytearray()),
        ("BASIC-32", "Singleton - Ellipsis", Ellipsis),
        ("BASIC-33", "Singleton - StopIteration", StopIteration),
    ]
