def get_container_type_cases():
    return [
        ("CONTAINER-01", "Empty list", []),
        ("CONTAINER-02", "Empty tuple", ()),
        ("CONTAINER-03", "Empty dict", {}),
        ("CONTAINER-04", "Empty set", set()),
        ("CONTAINER-05", "Empty frozenset", frozenset()),
        ("CONTAINER-06", "Simple list - [1, 2, 3]", [1, 2, 3]),
        ("CONTAINER-07", "Simple tuple - (1, 2, 3)", (1, 2, 3)),
        ("CONTAINER-08", "Simple dict - {'a': 1, 'b': 2}", {"a": 1, "b": 2}),
        ("CONTAINER-09", "Simple set - {1, 2, 3}", {1, 2, 3}),
        ("CONTAINER-10", "Simple frozenset - {1, 2, 3}", frozenset({1, 2, 3})),
        ("CONTAINER-11", "Mixed list", [1, "a", None, True, 3.14, b"abc"]),
        ("CONTAINER-12", "Mixed tuple", (1, "a", None, True, 3.14, b"abc")),
        (
            "CONTAINER-13",
            "Mixed dict",
            {"int": 1, "str": "a", "none": None, "bool": True},
        ),
        ("CONTAINER-14", "List containing dict", [{"a": 1}, {"b": 2}, {"c": 3}]),
        (
            "CONTAINER-15",
            "Dict containing list",
            {"numbers": [1, 2, 3], "letters": ["a", "b", "c"]},
        ),
        ("CONTAINER-16", "List containing tuple", [(1, 2), (3, 4), (5, 6)]),
        ("CONTAINER-17", "Tuple containing list", ([1, 2], [3, 4], [5, 6])),
        (
            "CONTAINER-18",
            "Dict containing tuple",
            {"point": (10, 20), "color": (255, 255, 255)},
        ),
        ("CONTAINER-19", "Dict containing set", {"values": {1, 2, 3}}),
        ("CONTAINER-20", "List containing set", [{1, 2}, {3, 4}, {5, 6}]),
        (
            "CONTAINER-21",
            "Nested list and dict",
            [{"items": [1, 2, 3]}, {"items": [4, 5, 6]}],
        ),
        (
            "CONTAINER-22",
            "Nested dict and tuple",
            {"user": {"id": 1, "roles": ("admin", "tester")}},
        ),
        ("CONTAINER-23", "Repeated values in list", [1, 1, 1, "a", "a", None, None]),
        ("CONTAINER-24", "Dict with integer keys", {1: "one", 2: "two", 3: "three"}),
        ("CONTAINER-25", "Dict with mixed keys", {"a": 1, 2: "b", (3, 4): "tuple_key"}),
        ("CONTAINER-26", "Slice - slice(1, 10, 2)", slice(1, 10, 2)),
        ("CONTAINER-27", "Slice - slice(None, 10, None)", slice(None, 10, None)),
        ("CONTAINER-28", "Slice - slice(None, None, -1)", slice(None, None, -1)),
        ("CONTAINER-29", "List containing slice", [slice(1, 5), slice(None, None, -1)]),
        (
            "CONTAINER-30",
            "Tuple containing slice",
            (slice(0, 10), slice(None, None, -1)),
        ),
        ("CONTAINER-31", "Dict containing slice value", {"range": slice(1, 10, 2)}),
    ]
